/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.biblioteca;

import static java.lang.Integer.parseInt;
import javax.swing.JPanel;

/**
 *
 * @author Diego Rodríguez Jacinto <drplaybasketball@gmail.com> 1DAW Número 26.
 */
public class PublicacionesForm extends javax.swing.JFrame {

    Biblioteca biblioteca;
    JPanel panelPorDefecto;

    /**
     * Creates new form PublicacionesForm
     */
    public PublicacionesForm() {
        initComponents();
        biblioteca = new Biblioteca();
        panelPorDefecto = (JPanel) getContentPane();
        cargarComboBox();
        ocultarPaneles();
    }

    //Metodo borrar
    public void borrarCampos() {
        campoAno.setText("");
        campoRevisor.setText("");
        campoDniAutor.setText("");
        campoISBN.setText("");
        campoMes.setText("");
        campoNumero.setText("");
        campoRevisado.setText("");
        campoTematica.setText("");
        campoTitulo.setText("");
        radioPrestado.setSelected(false);
        radioNoPrestado.setSelected(false);
    }

    //Cargar combobox
    public void cargarComboBox() {
        comboBox.addItem("Selecciona una: ");
        comboBox.addItem("Libro");
        comboBox.addItem("Investigacion");
    }

    //Ocultar paneles.
    public void ocultarPaneles() {
        panelInv.setVisible(false);
        panelRadio.setVisible(false);
        etiquetaDni.setVisible(false);
        campoDniAutor.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        comboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        campoISBN = new javax.swing.JTextField();
        campoTitulo = new javax.swing.JTextField();
        campoAno = new javax.swing.JTextField();
        campoDniAutor = new javax.swing.JTextField();
        botonMeter = new javax.swing.JButton();
        botonLimpiar = new javax.swing.JButton();
        botonBuscar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        etiquetaDni = new javax.swing.JLabel();
        panelRadio = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        radioPrestado = new javax.swing.JRadioButton();
        radioNoPrestado = new javax.swing.JRadioButton();
        panelInv = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        campoTematica = new javax.swing.JTextField();
        campoNumero = new javax.swing.JTextField();
        campoMes = new javax.swing.JTextField();
        campoRevisado = new javax.swing.JTextField();
        campoRevisor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Tipo Publicacion");

        botonMeter.setText("añadir");
        botonMeter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMeterActionPerformed(evt);
            }
        });

        botonLimpiar.setText("limpiar");
        botonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarActionPerformed(evt);
            }
        });

        botonBuscar.setText("buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ISBN");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Titulo");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Ano");

        etiquetaDni.setForeground(new java.awt.Color(0, 0, 0));
        etiquetaDni.setText("DniAutor");

        panelRadio.setBackground(new java.awt.Color(153, 153, 255));
        panelRadio.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Prestamo:");

        radioPrestado.setText("Prestado");

        radioNoPrestado.setText("No prestado");

        javax.swing.GroupLayout panelRadioLayout = new javax.swing.GroupLayout(panelRadio);
        panelRadio.setLayout(panelRadioLayout);
        panelRadioLayout.setHorizontalGroup(
            panelRadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRadioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRadioLayout.createSequentialGroup()
                .addGroup(panelRadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(radioNoPrestado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(radioPrestado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelRadioLayout.setVerticalGroup(
            panelRadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRadioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioPrestado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioNoPrestado)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        panelInv.setBackground(new java.awt.Color(255, 102, 0));
        panelInv.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel7.setText("Tematica");

        jLabel8.setText("Numero");

        jLabel9.setText("Mes");

        jLabel10.setText("Revisado");

        jLabel11.setText("Nombre Revisor");

        javax.swing.GroupLayout panelInvLayout = new javax.swing.GroupLayout(panelInv);
        panelInv.setLayout(panelInvLayout);
        panelInvLayout.setHorizontalGroup(
            panelInvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInvLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelInvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(62, 62, 62)
                .addGroup(panelInvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoTematica)
                    .addComponent(campoNumero)
                    .addComponent(campoMes)
                    .addComponent(campoRevisado)
                    .addComponent(campoRevisor, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        panelInvLayout.setVerticalGroup(
            panelInvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInvLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelInvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(campoTematica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(panelInvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(campoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(panelInvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(campoMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(panelInvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(campoRevisado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panelInvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(campoRevisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(etiquetaDni))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addComponent(botonBuscar))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(campoISBN, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                        .addComponent(campoTitulo)
                        .addComponent(campoAno)
                        .addComponent(campoDniAutor)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonMeter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonLimpiar)
                        .addGap(0, 19, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonSalir)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(panelRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelInv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonBuscar)
                            .addComponent(botonMeter)
                            .addComponent(botonLimpiar))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoDniAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiquetaDni))
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(botonSalir)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelInv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxActionPerformed
        switch (comboBox.getSelectedItem().toString()) {
            case "Libro":
                panelInv.setVisible(false);
                panelRadio.setVisible(true);
                etiquetaDni.setVisible(true);
                campoDniAutor.setVisible(true);
                break;
            case "Investigacion":
                panelInv.setVisible(true);
                panelRadio.setVisible(false);
                etiquetaDni.setVisible(false);
                campoDniAutor.setVisible(false);
                break;
            case "Selecciona una: ":
                panelInv.setVisible(false);
                panelRadio.setVisible(false);
                etiquetaDni.setVisible(false);
                campoDniAutor.setVisible(false);
                //Tambien: ocultarPaneles(); en ves de todo eso.
                break;
        }
        pack();
    }//GEN-LAST:event_comboBoxActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarActionPerformed
        borrarCampos();
    }//GEN-LAST:event_botonLimpiarActionPerformed

    private void botonMeterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMeterActionPerformed
        switch(comboBox.getSelectedItem().toString()){
            case "Libro":
                boolean radioLibro = false;
                if(radioNoPrestado.isSelected()){
                    radioLibro = false;
                }
                if(radioPrestado.isSelected()){
                    radioLibro = true;
                }
                Libro libro1 = new Libro(campoISBN.getText(), campoTitulo.getText(), parseInt(campoAno.getText()), 
                        radioLibro, campoDniAutor.getText());
                if(biblioteca.insertar(libro1)){
                    borrarCampos();
                }
                break;
            case "Investigacion":
                boolean revisado = false;
                if(campoRevisado.getText().equalsIgnoreCase("Si")){
                    revisado = true;
                }else if(campoRevisado.getText().equalsIgnoreCase("No")){
                    revisado = false;
                }
                //String tematica, boolean revisado, String revisor
                Investigacion investigacion1 = new Investigacion(campoISBN.getText(), campoTitulo.getText(), parseInt(campoAno.getText()), campoMes.getText(), 
                        parseInt(campoNumero.getText()), campoTematica.getText(), revisado, campoRevisor.getText());
                if(biblioteca.insertar(investigacion1)){
                    borrarCampos();
                }
                break;
        }
    }//GEN-LAST:event_botonMeterActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        String isbn = campoISBN.getText();
        Publicacion publicacionAux = biblioteca.buscarPublicacion(isbn);
        campoISBN.setText(publicacionAux.getCodigoISBN());
        campoTitulo.setText(publicacionAux.getTitulo());
        campoAno.setText(publicacionAux.getAnioPublicacion() + "");// de int a String.
        //Campos no comunes
        if(publicacionAux instanceof Libro){
            campoDniAutor.setText(((Libro) publicacionAux).getDniAutor());
            if(((Libro) publicacionAux).estaPrestado()){
                radioPrestado.setSelected(true);
            }else{
                radioNoPrestado.setSelected(true);
            }
        }
        if(publicacionAux instanceof Investigacion){
            campoTematica.setText(((Investigacion) publicacionAux).getTematica());
            campoNumero.setText(((Investigacion) publicacionAux).getNumero() + "");
            campoMes.setText(((Investigacion) publicacionAux).getMes() + "");
            if(((Investigacion) publicacionAux).isRevisado()){
                campoRevisado.setText("Si");
            }else{
                campoRevisado.setText("No");
            }
            campoRevisor.setText(((Investigacion) publicacionAux).getRevisor());
        }
    }//GEN-LAST:event_botonBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PublicacionesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PublicacionesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PublicacionesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PublicacionesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PublicacionesForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonLimpiar;
    private javax.swing.JButton botonMeter;
    private javax.swing.JButton botonSalir;
    private javax.swing.JTextField campoAno;
    private javax.swing.JTextField campoDniAutor;
    private javax.swing.JTextField campoISBN;
    private javax.swing.JTextField campoMes;
    private javax.swing.JTextField campoNumero;
    private javax.swing.JTextField campoRevisado;
    private javax.swing.JTextField campoRevisor;
    private javax.swing.JTextField campoTematica;
    private javax.swing.JTextField campoTitulo;
    private javax.swing.JComboBox<String> comboBox;
    private javax.swing.JLabel etiquetaDni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelInv;
    private javax.swing.JPanel panelRadio;
    private javax.swing.JRadioButton radioNoPrestado;
    private javax.swing.JRadioButton radioPrestado;
    // End of variables declaration//GEN-END:variables
}
